version: '3.8'
services:
  web-server-01:
    image: app-server
    container_name: web-server-01
    build: 
      context: ./
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - 8080:80
  web-server-02:
    image: app-server
    container_name: web-server-02
    build: 
      context: ./
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - 8081:80
  load-balancer:
    image: haproxy:alpine3.16
    container_name: load-balancer
    build: 
      context: ./
      dockerfile: Dockerfile.proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
    depends_on:
      - web-server-01
      - web-server-02