name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker App image
      run: docker build . --file Dockerfile.backend --tag ${{secrets.DOCKER_USER}}/demo-app-server:latest
    
    - name: Build the Docker Proxy image
      run: docker build . --file Dockerfile.proxy --tag ${{secrets.DOCKER_USER}}/demo-proxy-server:latest
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    
    - name: Docker Push Web Server
      run: docker push ${{secrets.DOCKER_USER}}/demo-app-server
    
    - name: Docker Push Proxy Server
      run: docker push ${{secrets.DOCKER_USER}}/demo-proxy-server
      
